# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Instagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instagram
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'SnapKit'
  pod 'Then'
  pod 'Kingfisher'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'RealmSwift'
  
  target 'InstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstagramUITests' do
    # Pods for testing
  end

end
