# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Moview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moview
  # UI
  pod 'SnapKit'
  pod 'Then'
  pod 'Kingfisher'
  pod 'SkeletonView'
  pod 'Hero'
  pod 'Toast-Swift'
  
  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  # API
  pod 'Alamofire'
  pod 'SwiftyJSON'

  # Conventions
  pod 'SwiftLint'
  pod 'R.swift'

  # Database
  pod 'RealmSwift'

end
